# This file was generated by GoReleaser. DO NOT EDIT.
cask "meufoco" do
  name "meufoco"
  desc "Interface CLI em modo TUI para gerenciar tarefas, áreas, projetos e espaços de trabalho"
  homepage "https://github.com/widia-io/widia-omni"
  version "0.0.3"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "meufoco"

  on_macos do
    on_intel do
      url "https://github.com/widia-io/widia-omni/releases/download/v#{version}/meufoco-cli_#{version}_darwin_amd64.tar.gz"
      sha256 "f6fc86ad2775540a968e5dec84d31f48a180da18fd30b4ae759f74f380d2e858"
    end
    on_arm do
      url "https://github.com/widia-io/widia-omni/releases/download/v#{version}/meufoco-cli_#{version}_darwin_arm64.tar.gz"
      sha256 "6c3239c89fb7c44925dd6abf89327fc144daf2f44978889a3e7c61367820b957"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/widia-io/widia-omni/releases/download/v#{version}/meufoco-cli_#{version}_linux_amd64.tar.gz"
      sha256 "f8b1396f0f9dbcae0028600b4b20ba1ae0ddb9aaf1581adec8acf48928d7dac8"
    end
    on_arm do
      url "https://github.com/widia-io/widia-omni/releases/download/v#{version}/meufoco-cli_#{version}_linux_arm64.tar.gz"
      sha256 "d9f3a1685816ec1d1314b97b48ee946cacca2d0abb0d5c5796de0f85ad0f5f4e"
    end
  end

  # No zap stanza required
end
