# This file was generated by GoReleaser. DO NOT EDIT.
cask "widia" do
  name "widia"
  desc "Interface CLI em modo TUI para gerenciar tarefas, áreas, projetos e espaços de trabalho"
  homepage "https://github.com/widia-io/widia-omni"
  version "0.0.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "widia"

  on_macos do
    on_intel do
      url "https://github.com/widia-io/widia-omni/releases/download/v#{version}/widia-cli_#{version}_darwin_amd64.tar.gz"
      sha256 "82cffa782093cdb2665fa9fd1e5cf4909a8f01f6103257004fe1d89b17af2fcc"
    end
    on_arm do
      url "https://github.com/widia-io/widia-omni/releases/download/v#{version}/widia-cli_#{version}_darwin_arm64.tar.gz"
      sha256 "6a4a3eedd7704374ea0817a56ec0de6522f69d7d3b4602da459de07ae95b6fc6"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/widia-io/widia-omni/releases/download/v#{version}/widia-cli_#{version}_linux_amd64.tar.gz"
      sha256 "92b7e366b1916d097306a03f2fa1978e46519ede6f2328394de8bc1628aa9ca1"
    end
    on_arm do
      url "https://github.com/widia-io/widia-omni/releases/download/v#{version}/widia-cli_#{version}_linux_arm64.tar.gz"
      sha256 "7e7a318cba0acd3ef773e89933944b62adc28f83f0db25557ed244ad30e2f329"
    end
  end

  # No zap stanza required
end
